# Introduction to Library

In [1]:
import torch

torch.manual_seed(10)

In [2]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [3]:
print(V[0])

print(V[0].item())

print(M[0])

print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [4]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-0.8173, -0.5556, -0.8267, -1.2970, -0.1974],
         [-0.9643, -0.5133,  2.6278, -0.7465,  1.0051],
         [-0.2568,  0.4765, -0.6652, -0.3627, -1.4504],
         [-0.2496,  0.8298,  1.1209,  0.9999,  1.1167]],

        [[ 1.0763, -0.0662,  0.1315,  0.1681,  0.0562],
         [ 0.2456,  0.9535,  0.3553,  0.2121, -0.3378],
         [-0.3536, -0.2729,  1.3290,  1.1974, -1.2645],
         [-0.4344, -2.1806, -1.1094, -2.0410,  0.0334]],

        [[-1.0805, -0.8832,  0.9741,  0.5632,  0.2979],
         [ 0.1442,  1.2385, -0.1170,  0.5876, -1.1603],
         [ 1.0045, -0.5749,  0.4541, -0.1225, -0.1627],
         [ 1.4592,  1.2487, -2.2774,  1.2525,  0.5467]]])


# Operations with Tensors

In [5]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [6]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.concat([x_1, y_1])
print(z_1)
print(z_1.shape)

# Concatenate columns
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)
print(z_2.shape)

tensor([[ 1.3687,  0.3852, -2.0651,  0.5798, -1.7677],
        [ 0.6419,  0.4829,  1.1083,  0.5820,  0.6164],
        [-1.4783, -1.9776,  0.8265, -0.6013, -0.9088],
        [-0.9017, -0.9700, -1.6733, -0.6607, -0.9986],
        [ 1.4816, -1.0823, -3.3556,  1.9240,  0.2508]])
torch.Size([5, 5])
tensor([[-1.6043, -1.1309,  0.3749,  1.6663,  0.6998, -1.1588,  1.2140, -0.2297],
        [ 1.2620,  0.3892, -0.6982, -0.3283,  0.7096,  0.4556,  0.2015, -0.1900]])
torch.Size([2, 8])


# Reshaping tensor

In [8]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))
print(x.view(2, 12).shape)
print(x.view(2, -1))
print(x.view(2, -1).shape)

tensor([[[ 0.0330,  0.9396,  1.3287,  0.0719],
         [ 1.0553, -0.8978, -2.2463, -0.3669],
         [-0.5246,  0.0565,  0.5084,  0.5053]],

        [[ 0.3078, -1.7432, -1.1199, -0.0032],
         [-0.8785, -0.8161, -1.5947, -1.4591],
         [-2.2393, -1.3974, -0.2388, -0.4498]]])
tensor([[ 0.0330,  0.9396,  1.3287,  0.0719,  1.0553, -0.8978, -2.2463, -0.3669,
         -0.5246,  0.0565,  0.5084,  0.5053],
        [ 0.3078, -1.7432, -1.1199, -0.0032, -0.8785, -0.8161, -1.5947, -1.4591,
         -2.2393, -1.3974, -0.2388, -0.4498]])
torch.Size([2, 12])
tensor([[ 0.0330,  0.9396,  1.3287,  0.0719,  1.0553, -0.8978, -2.2463, -0.3669,
         -0.5246,  0.0565,  0.5084,  0.5053],
        [ 0.3078, -1.7432, -1.1199, -0.0032, -0.8785, -0.8161, -1.5947, -1.4591,
         -2.2393, -1.3974, -0.2388, -0.4498]])
torch.Size([2, 12])


# Auto differentiation

In [9]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)

print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [10]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [11]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [12]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# default tensor has requires_grad=False
print(x.requires_grad, y.requires_grad)
z = x + y
print(z.grad_fn)

# Change the tensor into requires_grad=True
x = x.requires_grad_()
y = y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)

# Get the value of z only, not its long computation gradient history
new_z = z.detach()
print(new_z.grad_fn)
print(new_z.requires_grad)

False False
None
True
None
False


In [13]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False
